name: CI_action

on:
  push:
    branches: [main] 
  pull_request:
    branches: [main] 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    # Install and Test Backend
    - name: Install dependencies (Backend)
      run: npm install
      working-directory: ./backend

    - name: Run tests (Backend)
      run: npm test
      working-directory: ./backend

    # Install and Test Frontend
    - name: Install dependencies (Frontend)
      run: npm install
      working-directory: ./frontend

    - name: Run tests (Frontend)
      run: npm test
      working-directory: ./frontend

    # Build Frontend
    - name: Build (Frontend)
      run: npm run build
      working-directory: ./frontend
